<div id = "content">
	<div class = "container">
		<div class = "main_des">
			<h1><?php echo DOMAIN_NAME;?></h1>
			<div class = "notice">
				<div class = "notice_title notice_title1"><label><?php echo $notice_title;?></label></div>
				<div class = "notice_content"><?php echo $notice_content;?></div>
			</div>
			<div class = "describe">
				<div class = "des_about des_about1">
					<p class = "about-ico"><i class = "fa fa-thumbs-up fa-fw"></i></p>
					<p class = "about-title">功能强大</p>
					<p class = "about-content">集群管理和群娱乐为一体，必备神器呦</p>
				</div><div class = "des_about des_about2">
					<p class = "about-ico"><i class = "fa fa-graduation-cap fa-fw"></i></p>
					<p class = "about-title">智能灵活</p>
					<p class = "about-content">海量插件随心扩展，身材小巧智能敏捷</p>
				</div><div class = "des_about des_about3 container-last">
					<p class = "about-ico"><i class = "fa fa-cloud-upload fa-fw"></i></p>
					<p class = "about-title">放心无忧</p>
					<p class = "about-content">后台运行，机器人可以全天24小时在线</p>
				</div>
			</div>
			<div class = "notice">
				<div class = "notice_title notice_title2"><label>相关说明</label></div>
				<div class = "notice_content">
					<p><?php echo DOMAIN_NAME;?>采用Smart QQ接口，程序由PHP+MySQL开发</p>
					<p>密码经过md5加密后存入数据库，任何人都不会从本站知道您的机器人真实密码</p>
					<p>机器人在运行期间可以累积在线天数哦，但是您不能在机器人运行期间用电脑登录QQ，不然会把机器人挤下线，但是手机QQ可以登录，互不干扰</p>
					<p>机器人的强大之处在于海量的插件，如果您是开发者，可以看看插件<a href = "http://bbs.itpk.cn/forum.php?mod=viewthread&tid=49" target = "_blank">开发文档</a></p>
				</div>
			</div>
		</div>
	</div>
</div>